apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "jane" to read pods in the "default" namespace.
# You need to already have a Role named "pod-reader" in that namespace.
kind: RoleBinding
metadata:
  name: {{ include "keeper.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "keeper.serviceAccountName" . }}
roleRef:
  kind: Role #this must be Role or ClusterRole
  name: {{ include "keeper.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
