reservation:
  deployments:
    default:
      replicas: 1
#      nodeSelector: |
#        node.kubernetes.io/instance-type: c5d.xlarge
      schedule:
        timeZone: Europe/Bratislava
        up:
          cron: "0 8 * * 1-5"
          replicas: 1
        down:
          cron: "0 17 * * 1-5"
          replicas: 0
    unscheduled:
      replicas: 2
#      nodeSelector: |
#        node.kubernetes.io/instance-type: t3.large

overprovisioning:
  deployments:
    default:
      replicas: 3
      schedule:
        up:
          cron: "0 8 * * 1-5"
          replicas: 3
        down:
          cron: "0 17 * * 1-5"
          replicas: 0
