name: Cache Warmup

on:
  workflow_dispatch:
  push:
    branches:
      - main # caches from the main branch are shared with all other branches and pull requests

permissions:
  contents: read

env:
  # renovate: datasource=github-releases depName=jdx/mise
  MISE_VERSION: 2025.12.13

jobs:
  pre-commit:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false

      - name: Setup Mise
        uses: jdx/mise-action@6d1e696aa24c1aa1bcc1adea0212707c71ab78a8 # v3.6.1
        with:
          version: ${{ env.MISE_VERSION }}

      - name: Cache pre-commit
        uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        with:
          path: ~/.cache/pre-commit
          key: ${{ runner.os }}-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}-warmup
          restore-keys: ${{ runner.os }}-pre-commit-

      - name: Run pre-commit
        run: pre-commit install --install-hooks
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # required for GH API calls quota
